name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json
      - name: Cache NuGet packages
        uses: ./.github/actions/cache-nuget
      - name: Restore dependencies
        run: dotnet restore ./Light.TemporaryStreams.sln /p:ContinuousIntegrationBuild=true
      - name: Build
        run: dotnet build ./Light.TemporaryStreams.sln --configuration Release --no-restore /p:ContinuousIntegrationBuild=true
      - name: Test
        run: dotnet test ./Light.TemporaryStreams.sln --configuration Release --no-build --verbosity normal
